#!/bin/sh

for x in 5000 8000 10000 30000 50000 80000 100000
do
	for t in 01 02 03 04 05 06
	do
		echo === Test $t for $x nums ===
		if [ $t = 01 ] 
		then
			./randList $x > /tmp/$USER.nums
			echo First test data generated.
		elif [ $t = 02 ] 
		then
			sort -n /tmp/$USER.nums > dump
			echo Second - sorted with Dupes.
		elif [ $t = 03 ] 
		then
			sort -nr /tmp/$USER.nums > dump
			echo Third - reverse sorted with Dupes.
		elif [ $t = 04 ] 
		then
			seq $x | sort -R > dump
			echo Fourth - random with no Dupes.
		elif [ $t = 05 ] 
		then
			seq $x > dump
			echo Fifth - sorted with no Dupes.
		elif [ $t = 06 ] 
		then
			seq $x | sort -nr > dump
			echo Fourth - reverse sorted with no Dupes.
		fi
		
		(time ./useIntList < /tmp/$USER.nums > /dev/null) &> logs/Use$t$x.log
		(time sort -n < /tmp/$USER.nums > /dev/null) &> logs/Sort$t$x.log
		for i in 1 2 3 4 5 6 7 8 9
		do
			(time ./useIntList < /tmp/$USER.nums > /dev/null) &>> logs/Use$t$x.log
			(time sort -n < /tmp/$USER.nums > /dev/null) &>> logs/Sort$t$x.log
		done
	done
done